# Generated by Django 6.0.5 on 2026-08-28 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screen_type', models.CharField(choices=[('2D', 'Standard 2D'), ('3D', 'RealD 3D'), ('IMAX', 'IMAX 3D'), ('4DX', '4DX Motion')], default='2D', max_length=10)),
                ('total_seats', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_trailer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('age_rating', models.CharField(choices=[('U', 'Universal'), ('UA', 'Parental Guidance 12+'), ('A', 'Adults Only 18+'), ('R', 'Restricted')], default='UA', max_length=5)),
                ('release_date', models.DateField(db_index=True)),
                ('popularity_score', models.FloatField(db_index=True, default=0.0)),
                ('cast_members', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(related_name='movies', to='movies.language')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_verified_viewer', models.BooleanField(default=False)),
                ('reported_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('price_silver', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('price_gold', models.DecimalField(decimal_places=2, default=250.0, max_digits=8)),
                ('price_vip', models.DecimalField(decimal_places=2, default=400.0, max_digits=8)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.screen')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('total_screens', models.IntegerField(default=1)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='movies.city')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theater'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'release_date'], name='movies_movi_title_20a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity_score'], name='movies_movi_popular_1e6896_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['start_time'], name='movies_show_start_t_e420c7_idx'),
        ),
    ]
