# Generated by Django 6.0.5 on 2026-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='Unknown Director', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(default='NOW_SHOWING', max_length=20),
        ),
        migrations.AddField(
            model_name='showtime',
            name='format',
            field=models.CharField(default='2D', max_length=20),
        ),
        migrations.AddField(
            model_name='showtime',
            name='language',
            field=models.CharField(default='Tamil', max_length=50),
        ),
        migrations.AddField(
            model_name='theater',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='theater',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_type',
            field=models.CharField(choices=[('2D', 'Standard 2D'), ('3D', 'RealD 3D'), ('IMAX', 'IMAX 3D'), ('4DX', '4DX Motion'), ('Dolby Atmos', 'Dolby Atmos')], default='2D', max_length=20),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price_gold',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price_vip',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=8),
        ),
    ]
